# .github/workflows/feature.yml
name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
      - main

env:
  DOCKER_IMAGE: kviondocker/petapp:${{ github.sha }}
  MAVEN_OPTS: "-DskipTests=true"

jobs:
  build:
    uses: ./.github/workflows/javabuild.yml
    secrets: inherit

  sonar:
    needs: build
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  test:
    needs: sonar
    uses: ./.github/workflows/test.yml
    secrets: inherit

  imagepush:
    needs: test
    uses: ./.github/workflows/imagepush.yml
    secrets: inherit
