# .github/workflows/javabuild.yml
name: Build

on:
  workflow_call:

jobs:
  build:
    # Run on your "awsubuntu" self-hosted runner (labels: self-hosted, Linux, X64)
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-jar
          path: target/spring-petclinic-3.2.0-SNAPSHOT.jar

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trial0hcn9w.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Upload JAR to JFrog
        run: jf rt u "target/*.jar" "kirana_ci_artifact/"
