# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: build-server
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=KiranItagi666_GitHub_Actions_CICD -Dsonar.organization=KiranaItaagi -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2dbe436f12a766f531e04a905e8e555506110deb
