# .github/workflows/sonar.yml
name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    # Use your "awsubuntu" runner (labels: self-hosted, Linux, X64)
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Sonar Scanner data
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarCloud Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=KiranItagi666_GitHub_Actions_CICD \
            -Dsonar.organization=KiranaItaagi \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
